# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Variables Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/colors.conf

# Variables wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/ #
# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#general
general {

    gaps_in = 4
    gaps_out = 8
    border_size = 1
    col.active_border = $qs_foreground
    col.inactive_border = $qs_border
    layout = dwindle # master|dwindle

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#snap
    snap {
    	enabled = true
    }

}

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#group
group {
	col.border_active = $qs_foreground
	col.border_inactive = $qs_border
	col.border_locked_active = $qs_muted_foreground
	col.border_locked_inactive = $qs_border

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#groupbar
	groupbar {
		font_family = "Fira Sans"
		text_color = rgba(fafafaff)
		col.active = rgba(262626ff)
		col.inactive = rgba(171717ff)
		col.locked_active = rgba(262626ff)
		col.locked_inactive = rgba(171717ff)
	}
}
# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#misc
misc {
    font_family = "Fira Sans"
    splash_font_family = "Fira Sans"
    disable_hyprland_logo = true
    col.splash = rgba(fafafaff)
    background_color = rgba(0a0a0aff)
    enable_swallow = true
    swallow_regex = ^(cachy-browser|firefox|nautilus|nemo|thunar|btrfs-assistant.)$
    focus_on_activate = true
    vrr = 2
}

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#render
render {
   direct_scanout = true
}

# See https://wiki.hyprland.org/0.45.0/Configuring/Dwindle-Layout/ for more
dwindle {
    special_scale_factor = 0.8
    pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true
}

# See https://wiki.hyprland.org/0.45.0/Configuring/Master-Layout/ for more
master {
    new_status = master
    special_scale_factor = 0.8
}
